repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.9
    hooks:
      - id: ruff
      - id: ruff
        args: [--select, I, --fix]
      - id: ruff-format
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.5
    hooks:
      - id: check-github-workflows
        args: [--verbose]
      - id: check-metaschema
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-toml
      - id: check-yaml
      - id: check-xml
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii]
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
