[project]
name = "tg_hyper_librarian"
version = "0.1.0"
license = "MPL-2.0"
readme = "README.md"

authors = [
    { name = "k3-cat", email = "k3-cat@outlook.com" },
]

requires-python = ">=3.14"
dependencies = [
    "aiohttp>=3.13.5",
    "asyncstdlib>=3.14.0",
    "bitarray>=3.8.1",
    "caio>=0.9.25",
    "json-with-comments>=1.2.10",
    "orjson>=3.11.9",
    "typing-extensions>=4.15.0",
    "yarl>=1.24.2",
]

[project.urls]
Homepage = "https://github.com/k3-cat/tg_hyper_librarian"

[dependency-groups]
geolite = [
    "aiocsv>=1.4.0",
]
dev = [
    "ruff>=0.15.10",
]
test = [
    "pytest>=8.4.0",
    "pytest-asyncio>=1.4.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
# no-editable = true
default-groups = []

[tool.hatch.build.targets.wheel]
packages = [
    "src/c2luZy1ib3g",
    "src/tg_aio",
    "src/tg_h_l_",
]

[tool.hatch.build.targets.wheel.force-include]
"src/succinct.py" = "succinct.py"
"src/tg_ip.py" = "tg_ip.py"
"src/tg_utils.py" = "tg_utils.py"
